Canva embed banner
HKN-UCSD/hkn-portal pull request #102
Opened 2023-11-10 17:58 UTC by magikarp620

Change event banner source to Canva embed
Modify full calendar event display option(block, different color for draft events)

2023-11-14 23:19 UTC, MeghajV requested changes

2023-11-14 23:25 UTC, magikarp620 commented on .gitignore
yes

2023-11-14 23:31 UTC, MeghajV approved these changes

2023-11-17 18:10 UTC, MeghajV approved these changes

2023-11-17 18:56 UTC, merged