38 profile page editing
HKN-UCSD/hkn-portal pull request #147
Opened 2024-04-08 06:22 UTC by andrewzpu

Added edit profile page which allows users to edit and update preferred name, major, degree, graduation year, and car

2024-04-08 19:32 UTC, ryanyychen reviewed
When opening the profile edit page when 'Other' for Major or Degree is selected, the default selected should be 'Other' and what they have there should be entered.

2024-04-08 19:35 UTC, ryanyychen commented on myapp/api/forms.py
Please remove the comments on this page.

2024-04-10 04:24 UTC, andrewzpu commented on myapp/api/forms.py
Do you want me to remove the lines or just uncomment them?

2024-04-10 17:37 UTC, ryanyychen commented on frontend/src/Pages/ProfileEdit.svelte
> +        // maybe just give the whole form and have the view process it
Remove comment lines 85-87. Keep comments line 77-83 tho, thanks.

2024-04-17 17:08 UTC, ryanyychen requested changes
Please add:

Attempts to navigate away from the page should prompt a confirmation message if anything has been changed
Add in cancel button that returns user to profile page

2024-04-24 21:18 UTC, ryanyychen requested changes
Great work on implementing the cancel button! Thanks Andrew.

One more thing to add: could you have the leave page confirmation pop up not just when they click on the cancel button but also any attempts to leave or refresh the page?

2024-04-25 00:05 UTC, ryanyychen requested changes
Thanks for pushing the change quickly. The save and cancel buttons do not seem to be clickable anymore...

2024-04-27 22:46 UTC, ryanyychen approved these changes
Great work, thanks!

2024-05-08 05:00 UTC, merged