Formatting and code organization; event console updates without reloa…
HKN-UCSD/hkn-portal pull request #162
Opened 2024-04-24 23:22 UTC by ryan-s-lee

…d on events.

2024-04-24 23:23 UTC, ryan-s-lee commented
Actually wait a sec Edit Points stopped working

2024-04-27 22:52 UTC, ryanyychen approved these changes

2024-05-05 22:32 UTC, ryanyychen requested changes

2024-05-05 22:32 UTC, ryanyychen commented on frontend/src/Components/Events/CustomizableEventConsole.svelte
> +            console.log(indexedRows);
Can you remove this console.log line?

2024-05-05 22:32 UTC, ryanyychen commented on frontend/src/Components/Events/CustomizableEventConsole.svelte
> +                                            console.log("this gets printed");
remove this log statement

2024-05-14 02:21 UTC, ryan-s-lee commented on frontend/src/Components/Events/CustomizableEventConsole.svelte
> +                                            console.log("this gets printed");
Done

2024-05-14 02:22 UTC, ryan-s-lee commented on frontend/src/Components/Events/CustomizableEventConsole.svelte
> +            console.log(indexedRows);
Also done

2024-05-14 02:30 UTC, ryanyychen approved these changes

2024-05-14 02:34 UTC, merged